### ISSUE TITLE
登录以后发送不了信息

### ISSUE THREAD

**Issue by QQ-War** [duo/matrix-wechat-docker#1]
logs -f的日志如下：

time="2022-10-08T06:28:19+08:00" level=info msg="WechatManager starting to listen on 127.0.0.1:22222"
time="2022-10-08T06:28:19+08:00" level=info msg="Pinging websocket every 15s"
time="2022-10-08T06:28:19+08:00" level=info msg="Appservice websocket connected"
time="2022-10-08T06:29:14+08:00" level=info msg="No more files."
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: 没有那个文件或目录
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: 没有那个文件或目录
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: 没有那个文件或目录
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: 没有那个文件或目录
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: 没有那个文件或目录
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: 没有那个文件或目录
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: 没有那个文件或目录
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: 没有那个文件或目录
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
2022-10-07 23:29:48: basic_code_modules.cc:73: ERROR: Module rsaenh.dll could not be stored
2022-10-07 23:29:48: basic_code_modules.cc:73: ERROR: Module api-ms-win-downlevel-shell32-l1 could not be stored
2022-10-07 23:29:48: basic_code_modules.cc:73: ERROR: Module api-ms-win-downlevel-shell32-l1 could not be stored
2022-10-07 23:29:48: basic_code_modules.cc:73: ERROR: Module rsaenh.dll could not be stored

**Comment by QQ-War** [comment]
微信进程突然就没了。


user@matrix-wechat-agent:~$ ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
user           1       0  0 07:07 ?        00:00:00 /usr/bin/dumb-init /usr/bin/run.py
user           7       1  0 07:07 ?        00:00:00 /usr/bin/python3 /usr/bin/run.py
user           9       7  0 07:07 ?        00:00:00 [vncserver] <defunct>
user          10       7  0 07:07 ?        00:00:00 cmd /k /home/user/matrix-wechat-agent/matrix-wechat-agent.exe -h ws://matrix-wechat
user          14       1  5 07:07 ?        00:00:03 /opt/wine-stable/bin/wineserver
user          22       1  0 07:07 ?        00:00:00 /usr/bin/perl /usr/bin/vncserver -localhost no -xstartup /usr/bin/openbox :5
user          23      22  0 07:07 ?        00:00:00 /usr/bin/Xtigervnc :5 -rfbport 5905 -localhost=0 -SecurityTypes VncAuth,TLSVnc -Pas
user          25       1  0 07:07 ?        00:00:00 C:\windows\system32\services.exe
user          28       1  0 07:07 ?        00:00:00 C:\windows\system32\winedevice.exe
user          30       1  0 07:07 ?        00:00:00 C:\windows\system32\explorer.exe /desktop
user          35      22  0 07:07 ?        00:00:00 /usr/bin/openbox
user          48       1  0 07:07 ?        00:00:00 C:\windows\system32\plugplay.exe
user          56       1  1 07:07 ?        00:00:01 C:\windows\system32\winedevice.exe
user          67       1  0 07:07 ?        00:00:00 C:\windows\system32\svchost.exe -k LocalServiceNetworkRestricted
user          72       1  0 07:07 ?        00:00:00 /home/user/matrix-wechat-agent/matrix-wechat-agent.exe -h ws://matrix-wechat:20002
user          78       0  0 07:07 pts/0    00:00:00 bash
user          88       1 23 07:07 ?        00:00:11 C:\Program Files\Tencent\WeChat\WeChat.exe
user         136       1  1 07:07 ?        00:00:00 C:\users\user\Application Data\Tencent\WeChat\XPlugin\Plugins\XWeb\732\extracted\We
user         143       1  0 07:07 ?        00:00:00 C:\users\user\Application Data\Tencent\WeChat\XPlugin\Plugins\ThumbPlayer\3366\extr
user         172       1  0 07:07 ?        00:00:00 C:\users\user\Application Data\Tencent\WeChat\XPlugin\Plugins\XWeb\732\extracted\We
user         201       1  2 07:07 ?        00:00:01 C:\users\user\Application Data\Tencent\WeChat\XPlugin\Plugins\XWeb\732\extracted\We
user         333       1 25 07:08 ?        00:00:00 bugreport /buginfo:00000144:00000548:001F57F0:224 /extinfo:00000000
user         336      78  0 07:08 pts/0    00:00:00 ps -ef
user@matrix-wechat-agent:~$ ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
user           1       0  0 07:07 ?        00:00:00 /usr/bin/dumb-init /usr/bin/run.py
user           7       1  0 07:07 ?        00:00:00 /usr/bin/python3 /usr/bin/run.py
user           9       7  0 07:07 ?        00:00:00 [vncserver] <defunct>
user          10       7  0 07:07 ?        00:00:00 cmd /k /home/user/matrix-wechat-agent/matrix-wechat-agent.exe -h ws://matrix-wechat
user          14       1  8 07:07 ?        00:00:05 /opt/wine-stable/bin/wineserver
user          22       1  0 07:07 ?        00:00:00 /usr/bin/perl /usr/bin/vncserver -localhost no -xstartup /usr/bin/openbox :5
user          23      22  0 07:07 ?        00:00:00 /usr/bin/Xtigervnc :5 -rfbport 5905 -localhost=0 -SecurityTypes VncAuth,TLSVnc -Pas
user          25       1  0 07:07 ?        00:00:00 C:\windows\system32\services.exe
user          28       1  0 07:07 ?        00:00:00 C:\windows\system32\winedevice.exe
user          30       1  0 07:07 ?        00:00:00 C:\windows\system32\explorer.exe /desktop
user          35      22  0 07:07 ?        00:00:00 /usr/bin/openbox
user          48       1  0 07:07 ?        00:00:00 C:\windows\system32\plugplay.exe
user          56       1  1 07:07 ?        00:00:01 C:\windows\system32\winedevice.exe
user          67       1  0 07:07 ?        00:00:00 C:\windows\system32\svchost.exe -k LocalServiceNetworkRestricted
user          72       1  0 07:07 ?        00:00:00 /home/user/matrix-wechat-agent/matrix-wechat-agent.exe -h ws://matrix-wechat:20002
user          78       0  0 07:07 pts/0    00:00:00 bash
user         333       1 54 07:08 ?        00:00:04 bugreport /buginfo:00000144:00000548:001F57F0:224 /extinfo:00000000
user         341      78  0 07:08 pts/0    00:00:00 ps -ef
user@matrix-wechat-agent:~$

**Comment by duo** [comment]
收消息有没有问题?

然后看几个点吧

* `top` 看下负载, 如果很高, 那基本运行不会正常
*  设置下 shm_size 
*  /dev/dri 设置上看会不会好些

如果还不行, 那么还是找个 windows 来跑 agent 吧

**Comment by duo** [comment]
哦，还有就是找个配置
```
    security_opt:
      - seccomp:unconfined
```

**Comment by QQ-War** [comment]
除了/dev/dri都已经设置了。
我这个机器跑comwechat的那个docker没问题，这个不知道为啥微信进程直接崩…

**Comment by duo** [comment]
日志还真看不出啥来, 我这也不好复现...
要么尝试把下载最新的 SWeChatRobot.dll 以及编译个 master 分支的 matrix-wechat-agent.exe 替换看看吧

**Comment by QQ-War** [comment]
嗯，重新编译和下载以后是可以了。

**Comment by QQ-War** [comment]
好了 ，没啥问题了。看来就是默认镜像这几个文件太老了。。。。
另外，咨询一个问题，就是这个如果是多个matrix帐号，可以分别挂几个微信吗？

**Comment by duo** [comment]
目前的话, matrix-wechat 下可以接入一个 matrix-wechat-agent 连接, 然后 matrix-wechat-agent 是可以对多个 matrix 帐号分别微信的
我在 windows 下是有多开微信的, 但是不知道 docker wine 里能否正常多开...
